#!/usr/bin/env bash

# ==========================================================
# GENERATED BY UPGbuilder
# DO NOT EDIT MANUALLY
# ==========================================================
# UPGBUILDER_VERSION={{UPGBUILDER_VERSION}}
# TEMPLATE_NAME=template_update_bk.sh
# TEMPLATE_VERSION=1.0.0
# RULE_NAME=bk
# GENERATED_AT={{GENERATED_AT}}
# GENERATED_HOST={{HOSTNAME}}
# TARGET_USER={{TARGET_USER}}
# ==========================================================

set -uo pipefail

SRC_DIR="/home/itgo/UPG"
WEBAPPS_DIR="{{WEBAPPS_DIR}}"

WAR1="infomedica-server.war"
WAR2="raporty.war"

APP1="infomedica-server"
APP2="raporty"

BASE_LOG_DIR="${HOME}/UTILITY/LOG/UPDATE"
TODAY_LOG="$(date +%F)"
NOW_LOG="$(date +%H%M%S)"
RUN_LOG_DIR="${BASE_LOG_DIR}/${TODAY_LOG}"
LOG_FILE="${RUN_LOG_DIR}/run_${NOW_LOG}.log"

mkdir -p "${RUN_LOG_DIR}"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "========================================================================"
echo "[INFO] Start skryptu: $(basename "$0")"
echo "[INFO] Log: $LOG_FILE"
echo "[INFO] Data: $(date)"
echo "[INFO] Użytkownik: $(whoami)"
echo "[INFO] SRC_DIR: $SRC_DIR"
echo "[INFO] WEBAPPS_DIR: $WEBAPPS_DIR"
echo "========================================================================"

ask_continue() {
  local msg="${1:-Wystąpił błąd. Kontynuować dalsze kroki?}"
  read -r -p "$msg [t/N]: " ans
  if [[ ! "$ans" =~ ^[TtYy]$ ]]; then
    echo "[ABORT] Przerwano na żądanie użytkownika."
    exit 1
  fi
}

run_step() {
  local desc="$1"; shift
  echo
  echo "---------- KROK: $desc ----------"
  if "$@"; then
    echo "[OK] $desc"
  else
    local rc=$?
    echo "[ERROR] $desc (kod wyjścia: $rc)"
    ask_continue "Kontynuować mimo błędu kroku: \"$desc\"?"
  fi
}

step_verify_paths() {
  echo "[INFO] Weryfikacja katalogów SRC/DST"
  local d
  for d in "$SRC_DIR" "$WEBAPPS_DIR"; do
    if [[ ! -d "$d" ]]; then
      echo "[ERROR] Katalog nie istnieje: $d"
      return 1
    else
      echo "[INFO] OK: $d"
    fi
  done
}

step_remove_apps() {
  echo "[INFO] Usuwanie katalogów aplikacji (rozpakowane webappy)"
  local app target
  for app in "$APP1" "$APP2"; do
    target="$WEBAPPS_DIR/$app"
    if [[ -d "$target" ]]; then
      echo "[INFO] Usuwam katalog: $target"
      rm -rf --one-file-system -- "$target"
    else
      echo "[INFO] Pomijam (brak katalogu): $target"
    fi
  done
}

step_remove_old_wars() {
  echo "[INFO] Usuwanie starych plików WAR"
  local war target
  for war in "$WAR1" "$WAR2"; do
    target="$WEBAPPS_DIR/$war"
    if [[ -f "$target" ]]; then
      echo "[INFO] Usuwam plik: $target"
      rm -f -- "$target"
    else
      echo "[INFO] Pomijam (brak pliku): $target"
    fi
  done
}

step_check_new_wars() {
  echo "[INFO] Sprawdzanie dostępności nowych plików WAR w SRC"
  local war source
  local missing=0

  for war in "$WAR1" "$WAR2"; do
    source="$SRC_DIR/$war"
    if [[ ! -f "$source" ]]; then
      echo "[ERROR] Brak pliku źródłowego: $source"
      missing=1
    else
      echo "[INFO] OK: znaleziono $source"
    fi
  done

  [[ "$missing" -eq 0 ]]
}

step_copy_new_wars() {
  echo "[INFO] Kopiowanie nowych plików WAR (z zachowaniem czasu modyfikacji)"
  local war source target
  for war in "$WAR1" "$WAR2"; do
    source="$SRC_DIR/$war"
    target="$WEBAPPS_DIR/$war"
    echo "[INFO] Kopiuję: $source -> $target"
    cp -p -- "$source" "$target"
  done
}

run_step "Weryfikacja katalogów źródłowych i docelowych" step_verify_paths
run_step "Usuwanie katalogów aplikacji"                  step_remove_apps
run_step "Usuwanie starych plików WAR"                   step_remove_old_wars
run_step "Sprawdzanie dostępności nowych plików WAR"     step_check_new_wars
run_step "Kopiowanie nowych plików WAR"                  step_copy_new_wars

echo
echo "[INFO] Zakończono skrypt: $(date)"
echo "[INFO] Log zapisany w: $LOG_FILE"
echo "========================================================================"