#!/usr/bin/env bash

# ==========================================================
# GENERATED BY UPGbuilder
# DO NOT EDIT MANUALLY
# ==========================================================
# UPGBUILDER_VERSION={{UPGBUILDER_VERSION}}
# TEMPLATE_NAME=template_update_platforms.sh
# TEMPLATE_VERSION=1.1.0
# RULE_NAME=platforms
# GENERATED_AT={{GENERATED_AT}}
# GENERATED_HOST={{HOSTNAME}}
# TARGET_USER={{TARGET_USER}}
# ==========================================================

set -uo pipefail

BACKUP_DIR="/home/itgo/BACKUP"
SRV_DIR="/srv"

SCRIPT_DIR="$(cd -- "$(dirname "$0")" && pwd)"

KATALOG_ZRODLO="$SCRIPT_DIR/MAN/manager"
PLIK_ZRODLO="$SCRIPT_DIR/MAN/tomcat-users.xml"

APP_DIR="{{APP_DIR}}"
APP_LOG_DIR="{{APP_LOG_DIR}}"
ADM_DIR="{{ADM_DIR}}"
ADM_NEW_DIR="{{ADM_NEW_DIR}}"

BASE_LOG_DIR="${HOME}/UTILITY/LOG/UPDATE"
TODAY="$(date +%F)"
NOW="$(date +%H%M%S)"
RUN_LOG_DIR="${BASE_LOG_DIR}/${TODAY}"
LOG_FILE="${RUN_LOG_DIR}/run_${NOW}.log"

mkdir -p "${RUN_LOG_DIR}"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "========================================================================"
echo "[INFO] Start skryptu: $(basename "$0")"
echo "[INFO] Log: $LOG_FILE"
echo "[INFO] Data: $(date)"
echo "[INFO] Użytkownik: $(whoami)"
echo "[INFO] APP_DIR: ${APP_DIR}"
echo "[INFO] APP_LOG_DIR: ${APP_LOG_DIR}"
echo "========================================================================"

ask_continue() {
  local msg="${1:-Wystąpił błąd. Kontynuować dalsze kroki?}"
  read -r -p "$msg [t/N]: " ans
  if [[ ! "$ans" =~ ^[TtYy]$ ]]; then
    echo "[ABORT] Przerwano na żądanie użytkownika."
    exit 1
  fi
}

run_step() {
  local desc="$1"; shift
  echo
  echo "---------- KROK: $desc ----------"
  if "$@"; then
    echo "[OK] $desc"
  else
    local rc=$?
    echo "[ERROR] $desc (kod wyjścia: $rc)"
    ask_continue "Kontynuować mimo błędu kroku: \"$desc\"?"
  fi
}

PLATFORMS=()
PLATFORMS_NEW=()

discover_platforms() {
  local root dir base
  for root in /srv /opt; do
    [[ -d "$root" ]] || continue
    for dir in "$root"/IntegrationPlatform*; do
      [[ -d "$dir" ]] || continue
      base="$(basename "$dir")"
      [[ "$base" == *OLD* ]] && continue
      [[ "$base" == *_NEW ]] && continue
      PLATFORMS+=("$dir")
      PLATFORMS_NEW+=("${dir}_NEW")
    done
  done
}

step_discover_platforms() {
  echo "[0] Wykrywanie platform IntegrationPlatform..."
  discover_platforms

  if ((${#PLATFORMS[@]} == 0)); then
    echo "[ERROR] Nie znaleziono żadnych katalogów IntegrationPlatform w /srv ani /opt"
    return 1
  fi

  local i
  echo "[INFO] Wykryte platformy:"
  for i in "${!PLATFORMS[@]}"; do
    echo "    ${PLATFORMS[$i]}"
    echo "    -> NEW: ${PLATFORMS_NEW[$i]}"
  done
}

step_clear_logs() {
  echo "[1] Czyszczenie logów Tomcata..."
  local platform
  for platform in "${PLATFORMS[@]}"; do
    if [[ -d "${platform}/apache-tomcat/logs" ]]; then
      echo "    Czyszczę: ${platform}/apache-tomcat/logs"
      rm -rf "${platform}/apache-tomcat/logs/"* || true
    else
      echo "    [WARN] Brak katalogu logów: ${platform}/apache-tomcat/logs"
    fi
  done
}

NEW_BACKUP=""

step_prepare_backup() {
  echo "[2] Przygotowanie katalogu backupu..."
  mkdir -p "$BACKUP_DIR"

  local TODAY_BK
  TODAY_BK="$(date +'%d%m%Y')"
  NEW_BACKUP="$BACKUP_DIR/$TODAY_BK"
  echo "    Tworzę: $NEW_BACKUP"
  mkdir -p "$NEW_BACKUP"
}

step_cleanup_old_backups() {
  echo "[2b] Czyszczenie starych backupów, zostawiam 2 najnowsze w ${BACKUP_DIR}"
  mkdir -p "$BACKUP_DIR"

  mapfile -t TO_DEL < <(ls -1dt "${BACKUP_DIR}"/*/ 2>/dev/null | tail -n +3 || true)
  if ((${#TO_DEL[@]})); then
    printf '%s\0' "${TO_DEL[@]}" | xargs -0r rm -rf
    echo "[INFO] Usunięto stare backupy: ${TO_DEL[*]}"
  else
    echo "[INFO] Brak starych backupów do usunięcia."
  fi
}

step_move_platforms_to_backup() {
  echo "[3] Przenoszenie katalogów do backupu..."
  if [[ -z "${NEW_BACKUP:-}" ]]; then
    echo "[ERROR] NEW_BACKUP nie jest ustawiony – najpierw musi być wykonany krok backupu." >&2
    return 1
  fi

  local platform
  for platform in "${PLATFORMS[@]}"; do
    if [[ -d "$platform" ]]; then
      echo "    mv $platform -> $NEW_BACKUP/"
      mv "$platform" "$NEW_BACKUP"/
    else
      echo "    [WARN] Brak: $platform (pomijam)"
    fi
  done
}

step_copy_resources_to_new() {
  echo "[4] Kopiowanie zasobów do *_NEW (z katalogu skryptu: $SCRIPT_DIR)..."

  local target_new target_webapps target_conf

  if [[ -d "$KATALOG_ZRODLO" ]]; then
    for target_new in "${PLATFORMS_NEW[@]}"; do
      target_webapps="${target_new}/apache-tomcat/webapps"
      echo "    manager -> $target_webapps"
      mkdir -p "$target_webapps"
      cp -a -f "$KATALOG_ZRODLO" "$target_webapps"/
    done
  else
    echo "    [WARN] Brak katalogu źródłowego: $KATALOG_ZRODLO"
  fi

  if [[ -f "$PLIK_ZRODLO" ]]; then
    for target_new in "${PLATFORMS_NEW[@]}"; do
      target_conf="${target_new}/apache-tomcat/conf/tomcat-users.xml"
      echo "    tomcat-users.xml -> $target_conf"
      mkdir -p "$(dirname "$target_conf")"
      cp -f "$PLIK_ZRODLO" "$target_conf"
    done
  else
    echo "    [WARN] Brak pliku źródłowego: $PLIK_ZRODLO"
  fi
}

step_rename_new_dirs() {
  echo "[5] Zmiana nazw katalogów *_NEW..."
  local dir new_name
  for dir in "${PLATFORMS_NEW[@]}"; do
    if [[ -d "$dir" ]]; then
      new_name="${dir%_NEW}"
      echo "    $dir -> $new_name"
      mv "$dir" "$new_name"
    else
      echo "    [WARN] Brak katalogu: $dir (pomijam)"
    fi
  done
}

step_chmod_platforms() {
  echo "[6] Nadawanie uprawnień 775 dla wykrytych platform..."
  local platform
  for platform in "${PLATFORMS[@]}"; do
    if [[ -d "$platform" ]]; then
      echo "    chmod -R 775 $platform"
      sudo chmod -R 775 "$platform"
    else
      echo "    [WARN] Brak katalogu po rename: $platform"
    fi
  done
}

{{SPECIAL_PLATFORM_FUNCTIONS}}

run_step "Wykrywanie platform IntegrationPlatform"              step_discover_platforms
run_step "Czyszczenie logów Tomcata"                            step_clear_logs
run_step "Przygotowanie katalogu backupu (dzisiejszy)"          step_prepare_backup
run_step "Czyszczenie starych backupów (zostają 2)"             step_cleanup_old_backups
{{SPECIAL_PLATFORM_RUNS}}
run_step "Przenoszenie IntegrationPlatform_* do backupu"        step_move_platforms_to_backup
run_step "Kopiowanie manager/tomcat-users.xml do *_NEW"         step_copy_resources_to_new
run_step "Zmiana nazw katalogów *_NEW -> bez _NEW"              step_rename_new_dirs
run_step "Nadanie uprawnień 775 dla wykrytych platform"         step_chmod_platforms

echo
echo "[INFO] Zakończono skrypt: $(date)"
echo "[INFO] Log zapisany w: $LOG_FILE"
echo "========================================================================"