#!/usr/bin/env bash

# ==========================================================
# GENERATED BY UPGbuilder
# DO NOT EDIT MANUALLY
# ==========================================================
# UPGBUILDER_VERSION={{UPGBUILDER_VERSION}}
# TEMPLATE_NAME=template_update_platforms_zm.sh
# TEMPLATE_VERSION=1.0.0
# RULE_NAME=platforms_zm
# GENERATED_AT={{GENERATED_AT}}
# GENERATED_HOST={{HOSTNAME}}
# TARGET_USER={{TARGET_USER}}
# ==========================================================

set -euo pipefail

BACKUP_DIR="/home/itgo/BACKUP"
SRV_DIR="/srv"

UPG_DIR="/home/itgo/UPG/ZM"

PLATFORM_DIR="{{PLATFORM_DIR}}"
ZM_DOCKER_DIR="{{ZM_DOCKER_DIR}}"
APP_LOG_DIR="{{APP_LOG_DIR}}"

BASE_LOG_DIR="${HOME}/UTILITY/LOG/UPDATE"
TODAY_LOG="$(date +%F)"
NOW_LOG="$(date +%H%M%S)"
RUN_LOG_DIR="${BASE_LOG_DIR}/${TODAY_LOG}"
LOG_FILE="${RUN_LOG_DIR}/run_${NOW_LOG}.log"

mkdir -p "${RUN_LOG_DIR}"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "========================================================================"
echo "[INFO] Start skryptu: $(basename "$0")"
echo "[INFO] Log: $LOG_FILE"
echo "[INFO] Data: $(date)"
echo "[INFO] Użytkownik: $(whoami)"
echo "[INFO] PLATFORM_DIR: ${PLATFORM_DIR}"
echo "[INFO] ZM_DOCKER_DIR: ${ZM_DOCKER_DIR}"
echo "[INFO] APP_LOG_DIR: ${APP_LOG_DIR}"
echo "========================================================================"

ask_continue() {
  local msg="${1:-Wystąpił błąd. Kontynuować dalsze kroki?}"
  read -r -p "$msg [t/N]: " ans
  if [[ ! "$ans" =~ ^[TtYy]$ ]]; then
    echo "[ABORT] Przerwano na żądanie użytkownika."
    exit 1
  fi
}

run_step() {
  local desc="$1"; shift
  echo
  echo "---------- KROK: $desc ----------"
  if "$@"; then
    echo "[OK] $desc"
  else
    local rc=$?
    echo "[ERROR] $desc (kod wyjścia: $rc)"
    ask_continue "Kontynuować mimo błędu kroku: \"$desc\"?"
  fi
}

COMPOSE_KIND=""
COMPOSE_VER=""
COMPOSE_CMD=()

detect_compose() {
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    COMPOSE_KIND="v2"
    COMPOSE_VER="$(docker compose version 2>/dev/null | head -n 1)"
    COMPOSE_CMD=(docker compose)
    return 0
  fi

  if command -v docker-compose >/dev/null 2>&1; then
    COMPOSE_KIND="v1"
    COMPOSE_VER="$(docker-compose version 2>/dev/null | head -n 1)"
    COMPOSE_CMD=(docker-compose)
    return 0
  fi

  echo "[ERROR] Nie znaleziono ani 'docker compose', ani 'docker-compose'." >&2
  return 1
}

compose_has_flag() {
  local subcmd="$1"
  local flag="$2"
  "${COMPOSE_CMD[@]}" "$subcmd" --help 2>/dev/null | grep -q -- "$flag"
}

have_numfmt() { command -v numfmt >/dev/null 2>&1; }

to_bytes() {
  local s="${1// /}"
  s="${s//,/\.}"
  local num unit
  num="$(echo "$s" | sed -E 's/^([0-9]+(\.[0-9]+)?).*/\1/')"
  unit="$(echo "$s" | sed -E 's/^[0-9]+(\.[0-9]+)?(.*)$/\2/' | tr '[:upper:]' '[:lower:]')"
  [[ -z "$num" ]] && return 1
  case "$unit" in
    b|"")      awk -v n="$num" 'BEGIN{printf "%.0f\n", n}' ;;
    kb|kib)    awk -v n="$num" 'BEGIN{printf "%.0f\n", n*1024}' ;;
    mb|mib)    awk -v n="$num" 'BEGIN{printf "%.0f\n", n*1024*1024}' ;;
    gb|gib)    awk -v n="$num" 'BEGIN{printf "%.0f\n", n*1024*1024*1024}' ;;
    tb|tib)    awk -v n="$num" 'BEGIN{printf "%.0f\n", n*1024*1024*1024*1024}' ;;
    *)         return 1 ;;
  esac
}

bytes_to_human() {
  local b="${1:-0}"
  if have_numfmt; then
    numfmt --to=iec-i --suffix=B "$b"
  else
    echo "${b}B"
  fi
}

snapshot_compose_images() {
  local out
  if ! out="$("${COMPOSE_CMD[@]}" images 2>/dev/null)"; then
    return 0
  fi
  echo "$out" | awk '
    NR==1 {next}
    NF>=5 {
      repo=$2; tag=$3; size=$NF;
      if (repo != "" && tag != "" && size != "") print repo ":" tag "|" size
    }'
}

calc_total_delta_bytes() {
  local before_file="$1"
  local after_file="$2"
  awk -F'\\|' '
    FNR==NR { before[$1]=$2; next }
    { after[$1]=$2 }
    END {
      for (k in after) {
        b=before[k];
        a=after[k];
        if (a=="" ) continue;
        print k "|" b "|" a
      }
    }' "$before_file" "$after_file"
}

step_clear_logs() {
  echo "[1] Czyszczenie logów Tomcata dla platformy..."
  if [[ -d "${PLATFORM_DIR}/apache-tomcat/logs" ]]; then
    rm -rf "${PLATFORM_DIR}/apache-tomcat/logs/"* || true
  else
    echo "[WARN] Brak katalogu logów platformy: ${PLATFORM_DIR}/apache-tomcat/logs"
  fi

  echo "[INFO] Czyszczenie logów ZM Docker..."
  if [[ -d "${ZM_DOCKER_DIR}/log" ]]; then
    sudo rm -rf "${ZM_DOCKER_DIR}/log/"* || true
  else
    echo "[WARN] Brak katalogu logów ZM Docker: ${ZM_DOCKER_DIR}/log"
  fi

  echo "[INFO] Czyszczenie logów aplikacyjnych..."
  if [[ -d "${APP_LOG_DIR}" ]]; then
    sudo rm -rf "${APP_LOG_DIR}/"* || true
  else
    echo "[WARN] Brak katalogu logów aplikacyjnych: ${APP_LOG_DIR}"
  fi
}

TODAY_BK=""
NEW_BACKUP=""

step_prepare_backup() {
  echo "[2] Przygotowanie katalogu backupu..."
  mkdir -p "$BACKUP_DIR"

  local oldest
  oldest=$(ls -1dt "$BACKUP_DIR"/*/ 2>/dev/null | tail -n 1 || true)
  if [[ -n "${oldest:-}" ]]; then
    echo "    Usuwam najstarszy: $oldest"
    rm -rf -- "$oldest"
  else
    echo "    Brak wcześniejszych katalogów backupu – nic do usunięcia."
  fi

  TODAY_BK="$(date +'%d%m%Y')"
  NEW_BACKUP="$BACKUP_DIR/$TODAY_BK"
  echo "    Tworzę: $NEW_BACKUP"
  mkdir -p "$NEW_BACKUP"
}

step_move_platform_to_backup() {
  echo "[3] Przenoszenie katalogu platformy do backupu..."
  if [[ -z "${NEW_BACKUP:-}" ]]; then
    echo "[ERROR] Zmienna NEW_BACKUP nie jest ustawiona."
    return 1
  fi

  if [[ -d "$PLATFORM_DIR" ]]; then
    echo "    mv $PLATFORM_DIR -> $NEW_BACKUP/"
    mv "$PLATFORM_DIR" "$NEW_BACKUP"/
  else
    echo "    [WARN] Brak: $PLATFORM_DIR (pomijam)"
  fi
}

is_empty_src() {
  [[ ! -d "$UPG_DIR" ]] && return 0
  if find "$UPG_DIR" -mindepth 1 -print -quit 2>/dev/null | grep -q .; then
    return 1
  else
    return 0
  fi
}

step_sync_upg_to_zm() {
  echo "[4] Synchronizacja $UPG_DIR -> $ZM_DOCKER_DIR ..."
  sudo mkdir -p "$ZM_DOCKER_DIR"

  if is_empty_src; then
    echo "[WARN] Źródło '$UPG_DIR' jest puste lub nie istnieje."
    ask_continue "Kontynuować bez kopiowania z $UPG_DIR?"
    echo "[INFO] Pomijam kopiowanie, kontynuuję kolejne kroki."
    return 0
  fi

  echo "    rsync -> $ZM_DOCKER_DIR/"
  sudo rsync -a --delete "$UPG_DIR"/ "$ZM_DOCKER_DIR"/
}

step_rename_new_dirs() {
  echo "[5] Zmiana nazw katalogów *_NEW..."
  shopt -s nullglob
  local dir new_name
  for dir in "$SRV_DIR"/*_NEW "$OPT_DIR"/*_NEW; do
    [[ -d "$dir" ]] || continue
    new_name="${dir%_NEW}"
    echo "    $dir -> $new_name"
    mv "$dir" "$new_name"
  done
  shopt -u nullglob
}

step_set_permissions() {
  echo "[6] Nadawanie uprawnień 775 dla katalogu platformy..."
  if [[ -d "$PLATFORM_DIR" ]]; then
    sudo chmod -R 775 "$PLATFORM_DIR"
  else
    echo "[WARN] Brak katalogu po rename: $PLATFORM_DIR"
  fi
}

step_docker_cleanup_restart_and_pull() {
  echo "[7] Docker: cleanup + restart + compose pull (w $ZM_DOCKER_DIR)"

  command -v docker >/dev/null 2>&1 || {
    echo "[ERROR] 'docker' nie znaleziony w PATH." >&2
    return 1
  }

  cd "$ZM_DOCKER_DIR" || {
    echo "[ERROR] Nie mogę wejść do $ZM_DOCKER_DIR"
    return 1
  }

  detect_compose
  echo "[INFO] Compose wykryty: ${COMPOSE_KIND} | ${COMPOSE_VER}"

  echo "[INFO] Compose down: --rmi all --volumes --remove-orphans"
  sudo "${COMPOSE_CMD[@]}" down --rmi all --volumes --remove-orphans || true

  echo "[INFO] docker system prune -af"
  sudo docker system prune -af || true

  echo "[INFO] docker volume prune -f"
  sudo docker volume prune -f || true

  echo "[INFO] docker volume rm (wszystkie)"
  sudo docker volume ls -q | xargs -r sudo docker volume rm || true

  if command -v systemctl >/dev/null 2>&1; then
    echo "[INFO] Restart docker: systemctl restart docker"
    sudo systemctl restart docker
  else
    echo "[WARN] Brak systemctl – pomijam restart usługi docker."
  fi

  local tmp_before="" tmp_after="" tmp_pairs="" pull_log=""
  cleanup_tmp() {
    [[ -n "$tmp_before" ]] && rm -f "$tmp_before"
    [[ -n "$tmp_after"  ]] && rm -f "$tmp_after"
    [[ -n "$tmp_pairs"  ]] && rm -f "$tmp_pairs"
    [[ -n "$pull_log"   ]] && rm -f "$pull_log"
  }
  trap cleanup_tmp EXIT

  tmp_before="$(mktemp)"
  tmp_after="$(mktemp)"
  tmp_pairs="$(mktemp)"

  snapshot_compose_images >"$tmp_before" || true

  local t0 t1 elapsed
  t0="$(date +%s)"

  echo "[INFO] Pull (cichy jeśli dostępny)..."
  if compose_has_flag pull --quiet; then
    sudo "${COMPOSE_CMD[@]}" pull --quiet
  else
    pull_log="$(mktemp)"
    if ! sudo "${COMPOSE_CMD[@]}" pull >"$pull_log" 2>&1; then
      echo "[ERROR] Pull nieudany, log z pull poniżej:"
      cat "$pull_log" >&2
      return 1
    fi
  fi

  t1="$(date +%s)"
  elapsed="$((t1 - t0))"

  snapshot_compose_images >"$tmp_after" || true

  echo
  echo "---------------- PODSUMOWANIE PULL ----------------"
  echo "[INFO] Czas pull: ${elapsed}s"

  if [[ -s "$tmp_after" ]]; then
    echo "[INFO] Obrazy po pull:"
    awk -F'\\|' '{printf " - %s (size: %s)\n", $1, $2}' "$tmp_after"
  else
    echo "[WARN] Nie udało się pobrać listy obrazów z compose."
  fi

  if [[ -s "$tmp_before" && -s "$tmp_after" ]]; then
    calc_total_delta_bytes "$tmp_before" "$tmp_after" >"$tmp_pairs" || true
    local total_delta=0
    while IFS='|' read -r img bsz asz; do
      [[ -z "$asz" ]] && continue
      local bbytes=0 abytes=0
      bbytes="$(to_bytes "${bsz:-0}" 2>/dev/null || echo 0)"
      abytes="$(to_bytes "${asz:-0}" 2>/dev/null || echo 0)"
      if [[ "$abytes" =~ ^[0-9]+$ && "$bbytes" =~ ^[0-9]+$ && "$abytes" -gt "$bbytes" ]]; then
        total_delta=$((total_delta + (abytes - bbytes)))
      fi
    done <"$tmp_pairs"
    echo "[INFO] Szac. pobrano (przybliżenie): $(bytes_to_human "$total_delta")"
  else
    echo "[WARN] Brak danych do oszacowania pobranych MB."
  fi
  echo "---------------------------------------------------"
}

run_step "Czyszczenie logów"                               step_clear_logs
run_step "Przygotowanie backupu"                           step_prepare_backup
run_step "Przeniesienie platformy do backupu"              step_move_platform_to_backup
run_step "Synchronizacja UPG -> ZM Docker"                 step_sync_upg_to_zm
run_step "Zmiana nazw *_NEW"                               step_rename_new_dirs
run_step "Ustawianie uprawnień 775"                        step_set_permissions
run_step "Docker cleanup + restart + compose pull"         step_docker_cleanup_restart_and_pull

echo
echo "[INFO] Zakończono pomyślnie: $(date)"
echo "[INFO] Log zapisany w: $LOG_FILE"
echo "========================================================================"