#!/usr/bin/env bash

# ==========================================================
# GENERATED BY UPGbuilder
# DO NOT EDIT MANUALLY
# ==========================================================
# UPGBUILDER_VERSION={{UPGBUILDER_VERSION}}
# TEMPLATE_NAME=template_update_wildfly.sh
# TEMPLATE_VERSION=1.2.0
# RULE_NAME=wildfly
# GENERATED_AT={{GENERATED_AT}}
# GENERATED_HOST={{HOSTNAME}}
# TARGET_USER={{TARGET_USER}}
# ==========================================================

set -euo pipefail

BASE_LOG_DIR="${HOME}/UTILITY/LOG/UPDATE"
TODAY="$(date +%F)"
NOW="$(date +%H%M%S)"
RUN_LOG_DIR="${BASE_LOG_DIR}/${TODAY}"
LOG_FILE="${RUN_LOG_DIR}/run_${NOW}.log"

mkdir -p "${RUN_LOG_DIR}"
exec > >(tee -a "${LOG_FILE}") 2>&1

echo "===================================================="
echo "START: $(date)"
echo "Log file: ${LOG_FILE}"
echo "===================================================="

APP_DIR="{{APP_DIR}}"
APP_LOG_DIR="{{APP_LOG_DIR}}"

APP_BASE="$(basename "${APP_DIR}")"
APP_PARENT="$(dirname "${APP_DIR}")"
APP_OLD="${APP_PARENT}/${APP_BASE}_OLD"
APP_TMP="${APP_PARENT}/${APP_BASE}_TMP"

echo "[INFO] APP_DIR     : ${APP_DIR}"
echo "[INFO] APP_OLD     : ${APP_OLD}"
echo "[INFO] APP_TMP     : ${APP_TMP}"
echo "[INFO] APP_LOG_DIR : ${APP_LOG_DIR}"

step_verify_paths() {
  echo "[1] Weryfikacja katalogów..."
  local missing=0

  for d in "${APP_DIR}" "${APP_OLD}"; do
    if [[ -d "$d" ]]; then
      echo "    [OK] $d"
    else
      echo "    [ERROR] Brak katalogu: $d"
      missing=1
    fi
  done

  [[ "$missing" -eq 0 ]]
}

step_guard_wildfly_stopped() {
  echo "[1b] Sprawdzam, czy WildFly/JBoss dla APP_DIR jest zatrzymany..."

  if [[ ! -d /proc || ! -r /proc ]]; then
    echo "    [ERROR] Nie można potwierdzić zatrzymania aplikacji."
    echo "    [ERROR] Katalog /proc jest niedostępny lub nieczytelny."
    exit 1
  fi

  local proc_cmdline pid cmdline cmdline_lower short_cmd
  local wildfly_final="${APP_DIR}/wildfly-26.0.1.Final"
  local wildfly_dir="${APP_DIR}/wildfly"
  local checked_cmdlines=0
  local -a running_processes=()

  for proc_cmdline in /proc/[0-9]*/cmdline; do
    [[ -e "$proc_cmdline" ]] || continue
    [[ -r "$proc_cmdline" ]] || continue

    pid="${proc_cmdline#/proc/}"
    pid="${pid%%/*}"

    if ! cmdline="$(tr '\0' ' ' < "$proc_cmdline" 2>/dev/null)"; then
      continue
    fi
    [[ -n "$cmdline" ]] || continue
    checked_cmdlines=$((checked_cmdlines + 1))

    cmdline_lower="${cmdline,,}"
    if [[ "$cmdline" != *"$APP_DIR"* && "$cmdline" != *"$wildfly_final"* && "$cmdline" != *"$wildfly_dir"* ]]; then
      continue
    fi
    if [[ "$cmdline_lower" != *java* && "$cmdline_lower" != *wildfly* && "$cmdline_lower" != *jboss* && "$cmdline_lower" != *standalone* ]]; then
      continue
    fi

    short_cmd="$cmdline"
    if ((${#short_cmd} > 240)); then
      short_cmd="${short_cmd:0:237}..."
    fi
    running_processes+=("${pid}|${short_cmd}")
  done

  if ((checked_cmdlines == 0)); then
    echo "    [ERROR] Nie można potwierdzić zatrzymania aplikacji."
    echo "    [ERROR] Nie udało się odczytać żadnego /proc/<pid>/cmdline."
    exit 1
  fi

  if ((${#running_processes[@]})); then
    echo "    [ERROR] Wykryto uruchomiony proces Java/WildFly/JBoss powiązany z aktualizowanym APP_DIR."
    echo "    [ERROR] APP_DIR: ${APP_DIR}"
    local item found_pid found_cmd
    for item in "${running_processes[@]}"; do
      IFS='|' read -r found_pid found_cmd <<<"$item"
      echo "    [ERROR] PID: ${found_pid}"
      echo "    [ERROR] Komenda: ${found_cmd}"
    done
    echo "    [INFO] Zatrzymaj WildFly/aplikację przed aktualizacją i uruchom updater ponownie."
    exit 1
  fi

  echo "    [OK] Nie znaleziono uruchomionych procesów Java/WildFly/JBoss dla APP_DIR: ${APP_DIR}"
}

step_clear_logs() {
  echo "[2] Czyszczenie katalogu logów..."
  if [[ -d "${APP_LOG_DIR}" ]]; then
    echo "    Czyszczę: ${APP_LOG_DIR}"
    rm -rf "${APP_LOG_DIR:?}/"* || true
  else
    echo "    [WARN] Katalog logów nie istnieje: ${APP_LOG_DIR}"
  fi
}

step_cleanup_tmp() {
  echo "[3] Sprzątanie starego katalogu TMP..."
  if [[ -e "${APP_TMP}" ]]; then
    echo "    Usuwam: ${APP_TMP}"
    rm -rf "${APP_TMP}"
  else
    echo "    [INFO] Brak starego TMP: ${APP_TMP}"
  fi
}

step_swap_dirs() {
  echo "[4] Zamiana katalogów miejscami..."
  mv "${APP_DIR}" "${APP_TMP}"
  mv "${APP_OLD}" "${APP_DIR}"
  mv "${APP_TMP}" "${APP_OLD}"
  echo "    [OK] Zamiana zakończona sukcesem."
}

step_summary() {
  echo "[5] Podsumowanie końcowe..."
  echo "    APP_DIR  -> ${APP_DIR}"
  echo "    APP_OLD  -> ${APP_OLD}"
  echo "    APP_TMP  -> ${APP_TMP} (powinien już nie istnieć)"
  if [[ -d "${APP_DIR}" ]]; then
    echo "    [OK] Istnieje aktywny katalog: ${APP_DIR}"
  else
    echo "    [WARN] Brak aktywnego katalogu: ${APP_DIR}"
  fi
  if [[ -d "${APP_OLD}" ]]; then
    echo "    [OK] Istnieje katalog OLD: ${APP_OLD}"
  else
    echo "    [WARN] Brak katalogu OLD: ${APP_OLD}"
  fi
}

step_verify_paths
step_guard_wildfly_stopped
step_clear_logs
step_cleanup_tmp
step_swap_dirs
step_summary

echo "===================================================="
echo "STOP: $(date)"
echo "===================================================="
